export const faqs = [
    {
        question: "95%",
        app: "App 1",
        version: "1.2.0",
        answer: "PASS",
        updated: "2019-01-01",
        incidents: 1,
        fmea: "YES",
        gremlin: "NO",
        gamedays: "NO",
    },
    {
        question: "70%",
        app: "App 2",
        version: "1.0.0",
        answer: "PASS",
        updated: "2019-01-01",
        incidents: 0,
        fmea: "NO",
        gremlin: "YES",
        gamedays: "YES",
    },
    {
        question: "67%",
        app: "App 3",
        version: "0.0.9",
        answer: "FAIL",
        updated: "2019-01-01",
        incidents: 1,
        fmea: "NO",
        gremlin: "NO",
        gamedays: "NO",
    },
];
